# vim ft=yaml
# travis-ci.org definition for Nimfa tests
language: python

sudo: false

cache: pip
apt: true

addons:
  apt:
    packages:
    - build-essential
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - g++
    - gfortran
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - travis_wait pip install numpy
  - pip install python-coveralls pytest-cov pytest matplotlib
  - pip install pandas scikit-learn

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "export PYTHONPATH=$PYTHONPATH:."

script:
  - py.test --cov=polyssifier

after_success:
  - coveralls
